// Font handling for text items.
//
// Legacy Youzign models a text item's typeface with two attributes:
//   font     - the family name (e.g. "Arvo", "Open Sans")
//   fontType - the loading category; every stock Youzign face was a Google
//              webfont, serialized as "External Font".
// Bold / italic are SEPARATE boolean fields on the item, so the picker only
// ever chooses a *family* — weight/style come from the B / I toggles.
//
// This module is pure (no DOM). The editor app owns the actual <link> injection
// so we stay testable and the renderer package stays side-effect free.

import type { ItemPatch } from "./mutations.js";

/** The value legacy writes into `fontType` for any Google/webfont family. */
export const EXTERNAL_FONT = "External Font";

/**
 * Curated family list: every family observed in the fixtures (Arvo) plus a
 * popular Google Fonts set. Each family here ships regular (400) AND bold (700)
 * weights so the B toggle always resolves, and requesting them from the CSS2
 * API never 400s. Sorted for a calm, scannable dropdown.
 */
export const GOOGLE_FONTS: string[] = [
  "Abril Fatface",
  "Afacad",
  "Agbalumo",
  "Akaya Kanadaka",
  "Akshar",
  "Alata",
  "Albert Sans",
  "Alegreya",
  "Alegreya Sans",
  "Aleo",
  "Alfa Slab One",
  "Alice",
  "Amaranth",
  "Amatic SC",
  "Amiri",
  "Anaheim",
  "Andada Pro",
  "Andika",
  "Angkor",
  "Anonymous Pro",
  "Antic Didone",
  "Antic Slab",
  "Anton",
  "Antonio",
  "Anybody",
  "Archivo",
  "Archivo Black",
  "Archivo Narrow",
  "Arimo",
  "Arsenal",
  "Arvo",
  "Asap",
  "Asap Condensed",
  "Assistant",
  "Atkinson Hyperlegible",
  "Audiowide",
  "Averia Libre",
  "Bai Jamjuree",
  "Baloo 2",
  "Bangers",
  "Barlow",
  "Barlow Condensed",
  "Barlow Semi Condensed",
  "Baskervville",
  "Be Vietnam Pro",
  "Bebas Neue",
  "Belanosima",
  "Berkshire Swash",
  "Besley",
  "Bitter",
  "Bodoni Moda",
  "Bree Serif",
  "Brygada 1918",
  "Cabin",
  "Cabin Condensed",
  "Cairo",
  "Cairo Play",
  "Cantarell",
  "Cardo",
  "Catamaran",
  "Caveat",
  "Chakra Petch",
  "Changa",
  "Chivo",
  "Cinzel",
  "Comfortaa",
  "Commissioner",
  "Cormorant",
  "Cormorant Garamond",
  "Cormorant Infant",
  "Cormorant SC",
  "Crimson Pro",
  "Crimson Text",
  "Cuprum",
  "Dancing Script",
  "Dela Gothic One",
  "Didact Gothic",
  "DM Mono",
  "DM Sans",
  "DM Serif Display",
  "DM Serif Text",
  "Domine",
  "Dosis",
  "EB Garamond",
  "Encode Sans",
  "Encode Sans Condensed",
  "Encode Sans Expanded",
  "Encode Sans Semi Condensed",
  "Epilogue",
  "Exo",
  "Exo 2",
  "Figtree",
  "Fira Code",
  "Fira Mono",
  "Fira Sans",
  "Fira Sans Condensed",
  "Fira Sans Extra Condensed",
  "Fjalla One",
  "Fraunces",
  "Fredoka",
  "Gabarito",
  "Geologica",
  "Glegoo",
  "Gloock",
  "Gotu",
  "Great Vibes",
  "Hanken Grotesk",
  "Heebo",
  "Hind",
  "Hind Madurai",
  "Hind Siliguri",
  "IBM Plex Mono",
  "IBM Plex Sans",
  "IBM Plex Sans Arabic",
  "IBM Plex Sans Condensed",
  "IBM Plex Serif",
  "Inclusive Sans",
  "Inconsolata",
  "Inika",
  "Instrument Sans",
  "Instrument Serif",
  "Inter",
  "Inter Tight",
  "Istok Web",
  "Josefin Sans",
  "Josefin Slab",
  "Jost",
  "K2D",
  "Kanit",
  "Karla",
  "Khand",
  "Kumbh Sans",
  "Kurale",
  "Lato",
  "League Gothic",
  "League Spartan",
  "Libre Baskerville",
  "Libre Caslon Text",
  "Libre Franklin",
  "Literata",
  "Lobster",
  "Lora",
  "Luckiest Guy",
  "M PLUS 1",
  "M PLUS 1 Code",
  "M PLUS 1p",
  "M PLUS 2",
  "M PLUS Rounded 1c",
  "Manrope",
  "Marcellus",
  "Martel",
  "Martel Sans",
  "Mate",
  "Maven Pro",
  "Merriweather",
  "Merriweather Sans",
  "Mitr",
  "Montserrat",
  "Montserrat Alternates",
  "Montserrat Subrayada",
  "Mukta",
  "Mukta Mahee",
  "Mukta Malar",
  "Mukta Vaani",
  "Mulish",
  "Nanum Gothic",
  "Nanum Myeongjo",
  "Neuton",
  "Newsreader",
  "Niramit",
  "Noto Kufi Arabic",
  "Noto Naskh Arabic",
  "Noto Sans",
  "Noto Sans Arabic",
  "Noto Sans Bengali",
  "Noto Sans Devanagari",
  "Noto Sans Display",
  "Noto Sans Georgian",
  "Noto Sans Hebrew",
  "Noto Sans JP",
  "Noto Sans KR",
  "Noto Sans Mono",
  "Noto Sans SC",
  "Noto Sans Tamil",
  "Noto Serif",
  "Noto Serif Bengali",
  "Noto Serif Devanagari",
  "Noto Serif Display",
  "Noto Serif Georgian",
  "Noto Serif Hebrew",
  "Noto Serif JP",
  "Noto Serif KR",
  "Nunito",
  "Nunito Sans",
  "Old Standard TT",
  "Open Sans",
  "Oranienbaum",
  "Orbitron",
  "Oswald",
  "Outfit",
  "Overpass",
  "Overpass Mono",
  "Oxygen",
  "Pacifico",
  "Pathway Extreme",
  "Permanent Marker",
  "Philosopher",
  "Playfair",
  "Playfair Display",
  "Plus Jakarta Sans",
  "Podkova",
  "Poppins",
  "Pragati Narrow",
  "Prompt",
  "PT Sans",
  "PT Sans Caption",
  "PT Sans Narrow",
  "PT Serif",
  "Public Sans",
  "Quattrocento",
  "Quattrocento Sans",
  "Questrial",
  "Quicksand",
  "Rajdhani",
  "Raleway",
  "Readex Pro",
  "Recursive",
  "Red Hat Display",
  "Red Hat Mono",
  "Red Hat Text",
  "Red Rose",
  "Righteous",
  "Roboto",
  "Roboto Condensed",
  "Roboto Flex",
  "Roboto Mono",
  "Roboto Serif",
  "Roboto Slab",
  "Rokkitt",
  "Rubik",
  "Rubik Mono One",
  "Saira",
  "Saira Condensed",
  "Saira Extra Condensed",
  "Saira Semi Condensed",
  "Sarabun",
  "Satisfy",
  "Schibsted Grotesk",
  "Sen",
  "Shadows Into Light",
  "Signika",
  "Signika Negative",
  "Slabo 27px",
  "Sofia Sans",
  "Sofia Sans Condensed",
  "Sora",
  "Source Code Pro",
  "Source Sans 3",
  "Source Serif 4",
  "Space Grotesk",
  "Space Mono",
  "Spectral",
  "Spectral SC",
  "Spline Sans",
  "Spline Sans Mono",
  "Suez One",
  "Tajawal",
  "Teko",
  "Tinos",
  "Titan One",
  "Titillium Web",
  "Trirong",
  "Ubuntu",
  "Ubuntu Condensed",
  "Ubuntu Mono",
  "Unbounded",
  "Urbanist",
  "Varela Round",
  "Vollkorn",
  "Vollkorn SC",
  "Work Sans",
  "Yanone Kaffeesatz",
  "Yeseva One",
  "Ysabeau",
  "Ysabeau Infant",
  "Ysabeau Office",
  "Ysabeau SC",
  "Zeyada",
  "Zilla Slab",
];

/**
 * The typed patch for changing a text item's family. Writes `font` and pins
 * `fontType` to "External Font" (a Google webfont), matching legacy exactly so
 * the round-trip stays faithful.
 */
export function fontPatch(family: string): ItemPatch {
  return { font: family, fontType: EXTERNAL_FONT };
}

/** URL-encode a family for the Google Fonts CSS2 `family=` param. */
export function familyToParam(family: string): string {
  // spaces -> "+", request regular + bold so the B toggle resolves.
  return `${family.trim().replace(/ +/g, "+")}:wght@400;700`;
}

/**
 * Build a Google Fonts CSS2 stylesheet href for the given families. Returns
 * null for an empty list. Families are de-duplicated and ordered stably so the
 * same set always yields the same URL (cheap caching / dedupe key).
 */
export function googleFontsHref(families: string[]): string | null {
  const unique = Array.from(new Set(families.map((f) => f.trim()).filter(Boolean)));
  if (unique.length === 0) return null;
  const params = unique.map((f) => `family=${familyToParam(f)}`).join("&");
  return `https://fonts.googleapis.com/css2?${params}&display=swap`;
}
